### ISSUE TITLE
how can solve this endless error?

### ISSUE THREAD

**Issue by whatseob** [jdyjjj/All-in-One-Gait#3]
hi, i'm trying to run demo. but there's have some problems.
when numpy version is higher 1.20. then error message is below :

Traceback (most recent call last):
  File "demo/libs/main.py", line 6, in <module>
    from track import *
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/demo/libs/track.py", line 15, in <module>
    from tracker.byte_tracker import BYTETracker
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/demo/libs/tracker/byte_tracker.py", line 10, in <module>
    from tracker import matching
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/demo/libs/tracker/matching.py", line 7, in <module>
    from cython_bbox import bbox_overlaps as bbox_ious
  File "src/cython_bbox.pyx", line 12, in init cython_bbox
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/env_gait2/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

when numpy version is lower 1.20. then error message is below :

Traceback (most recent call last):
  File "demo/libs/main.py", line 6, in <module>
    from track import *
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/demo/libs/track.py", line 15, in <module>
    from tracker.byte_tracker import BYTETracker
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/demo/libs/tracker/byte_tracker.py", line 10, in <module>
    from tracker import matching
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/demo/libs/tracker/matching.py", line 4, in <module>
    import lap
  File "/mnt/ssd2T_1/yoseob/All-in-One-Gait/OpenGait/env_gait2/lib/python3.8/site-packages/lap/__init__.py", line 25, in <module>
    from ._lapjv import (
  File "__init__.pxd", line 199, in init lap._lapjv
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 96

how can i run this demo? please help me..

**Comment by whatseob** [comment]
i reinstall Cython and cython_bbox but still got error like : 

The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:

so i think if numpy verson over 1.20 caused error.
so can i get your numpy version and current pip list? 

Thanks

**Comment by xiphixiongfei** [comment]
> thanks

i have the same question， So could share your solutions？ thanks

**Comment by Lookey-Luo** [comment]
Hello, I also encountered similar problems during the environment configuration process. When the numpy version is 1.24.4, an error occurs when running the demo: AttributeError: module 'numpy' has no attribute 'float'. When the numpy version is 1.21.1, an error occurs when running the demo: ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 88, got 96. When the numpy version is 1.22.0, an error occurs when running the demo: ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it). When the numpy version is 1.23.0, an error occurs when running the demo: ModuleNotFoundError: No module named 'paddle.fluid'.
May I ask what version of numpy I should install? I have tried installing cython==3.0.11 and cython-bbox==0.1.3, but the problem has not been solved. The following are the versions of all the third-party libraries I have currently installed:
Name Version Build Channel
_libgcc_mutex 0.1 main
_openmp_mutex 5.1 1_gnu
absl-py 2.1.0 pypi_0 pypi
anyio 4.5.2 pypi_0 pypi
astor 0.8.1 pypi_0 pypi
babel 2.16.0 pypi_0 pypi
bce-python-sdk 0.9.23 pypi_0 pypi
beautifulsoup4 4.12.3 pypi_0 pypi
blinker 1.8.2 pypi_0 pypi
ca-certificates 2024.9.24 h06a4308_0
cachetools 5.5.0 pypi_0 pypi
certifi 2024.8.30 pypi_0 pypi
charset-normalizer 3.4.0 pypi_0 pypi
click 8.1.7 pypi_0 pypi
coloredlogs 1.5.0.1 pypi_0 pypi
contourpy 1.1.1 pypi_0 pypi
cycler 0.1.2.1 pypi_0 pypi
cython 3.0.11 pypi_0 pypi
cython-bbox 0.1.3 pypi_0 pypi
decorator 5.1.1 pypi_0 pypi
exceptiongroup 1.2.2 pypi_0 pypi
filelock 3.16.1 pypi_0 pypi
filterpy 1.4.5 pypi_0 pypi
flask 3.0.3 pypi_0 pypi
flask-babel 4.0.0 pypi_0 pypi
flatbuffers 24.3.25 pypi_0 pypi
fonttools 4.55.0 pypi_0 pypi
future 1.0.0 pypi_0 pypi
gdown 5.2.0 pypi_0 pypi
google-auth 2.36.0 pypi_0 pypi
google-auth-oauthlib 1.0.0 pypi_0 pypi
grpcio 1.68.0 pypi_0 pypi
h11 0.14.0 pypi_0 pypi
h5py 3.11.0 pypi_0 pypi
httpcore 1.0.7 pypi_0 pypi
httpx 0.27.2 pypi_0 pypi
humanfriendly 10.0 pypi_0 pypi
idna 3.10 pypi_0 pypi
imageio 2.35.1 pypi_0 pypi
importlib-metadata 8.5.0 pypi_0 pypi
importlib-resources 6.4.5 pypi_0 pypi
itsdangerous 2.2.0 pypi_0 pypi
jinja2 3.1.4 pypi_0 pypi
joblib 1.4.2 pypi_0 pypi
kiwisolver 1.4.7 pypi_0 pypi
kornia 0.7.3 pypi_0 pypi
kornia-rs 0.1.7 pypi_0 pypi
lap 0.4.0 pypi_0 pypi
lazy-loader 0.4 pypi_0 pypi
libedit 3.1.20230828 h5eee18b_0
libffi 3.2.1 hf484d3e_1007
libgcc-ng 11.2.0 h1234567_1
libgomp 11.2.0 h1234567_1
libstdcxx-ng 1.2.0 h1234567_1
loguru 0.7.2 pypi_0 pypi
markdown 3.7 pypi_0 pypi
markdown-it-py 3.0.0 pypi_0 pypi
markupsafe 2.1.5 pypi_0 pypi
matplotlib 3.7.5 pypi_0 pypi
mdurl 0.1.2 pypi_0 pypi
motmetrics 1.4.0 pypi_0 pypi
mpmath 1.3.0 pypi_0 pypi
ncurses 6.4 h6a678d5_0
networkx 3.1 pypi_0 pypi
ninja 1.11.1.2 pypi_0 pypi
numpy 1.24.4 pypi_0 pypi
oauthlib 3.2.2 pypi_0 pypi
onnx 1.8.1 pypi_0 pypi
onnx-simplifier 0.3.5 pypi_0 pypi
onnxoptimizer 0.3.13 pypi_0 pypi
onnxruntime 1.8.0 pypi_0 pypi
opencv-python 4.5.5.64 pypi_0 pypi
openssl 1.1.1w h7f8727e_0
opt-einsum 3.3.0 pypi_0 pypi
packaging 24.2 pypi_0 pypi
paddlepaddle-gpu 2.6.2 pypi_0 pypi
pandas 2.0.3 pypi_0 pypi
pillow 10.4.0 pypi_0 pypi
pip 24.2 py38h06a4308_0
prettytable 3.11.0 pypi_0 pypi
protobuf 5.28.3 pypi_0 pypi
psutil 6.1.0 pypi_0 pypi
pyasn1 0.6.1 pypi_0 pypi
pyasn1-modules 0.4.1 pypi_0 pypi
pycocotools 2.0.7 pypi_0 pypi
pycryptodome 3.21.0 pypi_0 pypi
pygments 2.18.0 pypi_0 pypi
pyparsing 3.1.4 pypi_0 pypi
pysocks 1.7.1 pypi_0 pypi
python 3.8.0 h0371630_2
python-dateutil 2.9.0.post0 pypi_0 pypi
pytz 2024.2 pypi_0 pypi
pywavelets 1.4.1 pypi_0 pypi
pyyaml 6.0.2 pypi_0 pypi
rarfile 4.2 pypi_0 pypi
readline 7.0 h7b6447c_5
requests 2.32.3 pypi_0 pypi
requests-oauthlib 2.0.0 pypi_0 pypi
rich 13.9.4 pypi_0 pypi
rsa 4.9 pypi_0 pypi
scikit-image 0.21.0 pypi_0 pypi
scikit-learn 1.3.2 pypi_0 pypi
scipy 1.10.1 pypi_0 pypi
setuptools 59.8.0 pypi_0 pypi
six 1.16.0 pypi_0 pypi
sniffio 1.3.1 pypi_0 pypi
soupsieve 2.6 pypi_0 pypi
sqlite 3.33.0 h62c20be_0
sympy 1.13.3 pypi_0 pypi
tabulate 0.9.0 pypi_0 pypi
tensorboard 2.14.0 pypi_0 pypi
tensorboard-data-server 0.7.2 pypi_0 pypi
thop 0.1.1-2209072238 pypi_0 pypi
threadpoolctl 3.5.0 pypi_0 pypi
tifffile 2023.7.10 pypi_0 pypi
tk 8.6.14 h39e8969_0
torch 1.12.1 pypi_0 pypi
torchaudio 0.12.1 pypi_0 pypi
torchvision 0.13.1 pypi_0 pypi
tqdm 4.67.1 pypi_0 pypi
typing-extensions 4.12.2 pypi_0 pypi
tzdata 2024.2 pypi_0 pypi
urllib3 2.2.3 pypi_0 pypi
visualdl 2.5.3 pypi_0 pypi
wcwidth 0.2.13 pypi_0 pypi
werkzeug 3.0.6 pypi_0 pypi
wheel 0.44.0 py38h06a4308_0
xmltodict 0.14.2 pypi_0 pypi
xz 5.4.6 h5eee18b_1
yolox 0.3.0 pypi_0 pypi
zipp 3.20.2 pypi_0 pypi
zlib 1.2.13 h5eee18b_1
